projects:
  Codegen Project:
    schemaPath: schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: ucvkf5mrsjfollix2ifq4zksw4
        frontend: javascript
        framework: react
        maxDepth: 5
